# Generated by Django 5.0.6 on 2026-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='unlock_notifications_sent',
            field=models.BooleanField(default=False),
        ),
    ]
