# Generated by Django 5.0.6 on 2026-05-08 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0006_sync_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='pin_lock',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'PIN must be exactly 4 digits')]),
        ),
    ]
